"""empty message

Revision ID: b49a929484f7
Revises: 5e0399731093
Create Date: 2020-05-21 16:49:59.181419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49a929484f7'
down_revision = '5e0399731093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('code', sa.String(), nullable=True))
    op.add_column('snippet', sa.Column('code_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'code_type')
    op.drop_column('snippet', 'code')
    # ### end Alembic commands ###
